### PR TITLE
Fix the bug of unregisterAsWatcher

### LINKED ISSUE #367: unregisterAsWatcher()
Properly invoke unregisterAsWatcher() when a constraint is destroyed. 
In particular, in MaxConstraint, the list of _elements can change over time, so make sure to unregister the original set.

### PR DESCRIPTION
**Pull request by tagomaru**
Signed-off-by: tagomaru <tagomaru@users.noreply.github.com>

This PR is going to resolve #367 .

### CODE REVIEW

File: src/engine/MaxConstraint.cpp [hunk 1]
```diff
@@ -34,6 +34,7 @@
 MaxConstraint::MaxConstraint( unsigned f, const Set<unsigned> &elements )
     : _f( f )
     , _elements( elements )
+    , _initialElements ( elements )
```
Comment (guykatzz) [inline src/engine/MaxConstraint.cpp:37]: Cosmetics: please remove the space before the '('

**Review by guykatzz — APPROVED** [review]

**Comment by guykatzz** [comment]
Apart from my tiny comment, looks good to me.

File: src/engine/MaxConstraint.cpp (hunk 1 above)
Comment (tagomaru) [reply src/engine/MaxConstraint.cpp]: Yes. I did.
